version: "2"
services:
  web:
    #volumes_from:
    #  - container:docker-mac-sync:rw # will be mounted on /var/www
    volumes:
      - docker-mac-sync:/app:rw

volumes:
    docker-mac-sync:
        external: true

  
